### ISSUE TITLE
New manifest format results in `Error: author is not a string`

### ISSUE THREAD

**Issue by djahandarie** [cardinalby/webext-buildtools-chrome-webstore-upload-action#10]
We [updated our manifest](https://github.com/themoeway/yomitan/pull/614) to match the type being enforced here:
https://developer.chrome.com/docs/extensions/reference/manifest/author

We had to do this to upgrade to the new `"@types/chrome": "^0.0.260"` npm package (not sure if it was introduced in exactly this version, but somewhere between 254 and 260)

But this action seems to break with that new format:
```
Run cardinalby/webext-buildtools-chrome-webstore-upload-action@8db7a005529498d95d3e2e0166f6f4050d2b96a5
  with:
    zipFilePath: yomitan-chrome-dev.zip
    extensionId: ***
    apiAccessToken: ***
    waitForUploadCheckCount: 10
    waitForUploadCheckIntervalMs: 180000
info:    Manifest input is not set, reading from zip...
Error: Error: author is not a string
```

(I'm not sure where exactly that error is coming from, I wasn't able to find it via some GitHub searching...)

**Comment by cardinalby** [comment]
Hi! Try again from master or v1, I removed the unnecessary validations

**Comment by djahandarie** [comment]
It worked!! Thank you so much as always :pray:
