### ISSUE TITLE
extension upload error

### ISSUE THREAD

**Issue by p0we7** [cardinalby/webext-buildtools-chrome-webstore-upload-action#3]
Hello,

I used this workflow to upload chrome web store extension, but i got this error `Can't upload extension. Enabling 2 step verification on your account is required for security purposes. Please visit https://www.google.com/landing/2step to set it up.`.

The yaml config file on [here](https://github.com/sciooga/v2ex-plus/actions/runs/1153297263/workflow).

Can you help me get more information to solve this problem?

**Comment by p0we7** [comment]
I don't know why before using this workflow do not need two step verification.

And now i set the two step verification, everything is working fine.

**Comment by cardinalby** [comment]
Hi! Thanks for the usage of my actions and I'm happy to hear you have already solved the issue. Recently Google started to enforce 2-step verification for Chrome Web Store accounts. More details here: https://developer.chrome.com/blog/policy-update-2sv/
